environment:
    script:
    - echo "instruksi untuk install module yang dibutuhkan"
    - echo "instruksi untuk setup environment variable"

test:
    script:
    - mkdir -p ../database
    - mkdir -p ../static
    - mkdir -p ../virtualenv
    - virtualenv --python=python3 ../virtualenv
    - ../virtualenv/bin/pip install -r requirements.txt
    - ../virtualenv/bin/python3 manage.py collectstatic --noinput
    - ../virtualenv/bin/python3 manage.py migrate --noinput
    - python3 manage.py test
    - echo "instruksi untuk test UI"
    only :
    - master

deploy:
    script:
    - echo "instruksi untuk migrasi data"
    - echo "instruksi untuk menjalankan aplikasi/service"
    only:
    - master

